[package]
name = "dotfile"
version = "0.1.0"
authors = ["Edward Shen <code@eddie.sh>"]
edition = "2018"

[dependencies]
clap = {version = "2.32", features = ["yaml"]}
dirs = "1.0.4"
toml = "0.4.2"
serde = {version = "1.0", features = ["derive"]}